name: metropolitan_investment
description: "Metropolitan Investment - Professional Investment Management Platform."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.8.1

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # UI Dependencies
  cupertino_icons: ^1.0.8
  material_design_icons_flutter: ^7.0.7296
  
  # Firebase
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.0.0
  cloud_functions: ^6.0.0
  firebase_analytics: ^12.0.0
  firebase_storage: ^13.0.0
  
  # State Management
  provider: ^6.1.2
  riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1
  
  # Navigation
  go_router: ^16.1.0
  
  # Charts and analytics
  fl_chart: ^0.68.0
  syncfusion_flutter_charts: ^30.2.4
  
  # Calendar
  time_planner: ^0.1.2+1
  syncfusion_flutter_datagrid: ^30.2.4
  
  # Networking
  http: ^1.2.2
  dio: ^5.7.0
  
  # Local Storage
  shared_preferences: ^2.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Date/Time
  intl: ^0.20.2
  table_calendar: ^3.1.2
  
  # Utils
  uuid: ^4.5.1
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  lottie: ^3.1.2
  flutter_svg: ^2.0.10+1
  
  # Form handling
  form_validator: ^2.1.1
  email_validator: ^2.1.17
  
  # Security
  html: ^0.15.4
  
  # File handling
  file_picker: ^10.2.3
  path_provider: ^2.1.4
  excel: ^4.0.6
  csv: ^6.0.0
  
  # Export/PDF
  pdf: ^3.11.1
  printing: ^5.13.2
  
  # Rich text editor
  flutter_quill: ^11.4.2
  vsc_quill_delta_to_html: ^1.0.5
  flutter_colorpicker: ^1.1.0
  flutter_localizations:
    sdk: flutter
  
  # Audio
  audioplayers: ^6.1.0
  
  # Responsive UI
  responsive_framework: ^1.5.1
  
  # Currency
  currency_formatter: ^2.2.0
  flutter_html: ^3.0.0
  html_editor_enhanced: ^2.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # Assets
  assets:
    - assets/logos/
    - assets/audio/
    

  # Local fonts configuration for Enhanced Email Editor
fonts:
  - family: CrimsonText
    fonts:
      - asset: assets/fonts/crimson_text_400.ttf
        weight: 400
      - asset: assets/fonts/crimson_text_600.ttf
        weight: 600
      - asset: assets/fonts/crimson_text_700.ttf
        weight: 700
  - family: FiraSans
    fonts:
      - asset: assets/fonts/fira_sans_300.ttf
        weight: 300
      - asset: assets/fonts/fira_sans_400.ttf
        weight: 400
      - asset: assets/fonts/fira_sans_500.ttf
        weight: 500
      - asset: assets/fonts/fira_sans_600.ttf
        weight: 600
      - asset: assets/fonts/fira_sans_700.ttf
        weight: 700
  - family: Inter
    fonts:
      - asset: assets/fonts/inter_300.ttf
        weight: 300
      - asset: assets/fonts/inter_400.ttf
        weight: 400
      - asset: assets/fonts/inter_500.ttf
        weight: 500
      - asset: assets/fonts/inter_600.ttf
        weight: 600
      - asset: assets/fonts/inter_700.ttf
        weight: 700
  - family: Lato
    fonts:
      - asset: assets/fonts/lato_300.ttf
        weight: 300
      - asset: assets/fonts/lato_400.ttf
        weight: 400
      - asset: assets/fonts/lato_700.ttf
        weight: 700
  - family: LibreBaskerville
    fonts:
      - asset: assets/fonts/libre_baskerville_400.ttf
        weight: 400
      - asset: assets/fonts/libre_baskerville_700.ttf
        weight: 700
  - family: Merriweather
    fonts:
      - asset: assets/fonts/merriweather_300.ttf
        weight: 300
      - asset: assets/fonts/merriweather_400.ttf
        weight: 400
      - asset: assets/fonts/merriweather_500.ttf
        weight: 500
      - asset: assets/fonts/merriweather_600.ttf
        weight: 600
      - asset: assets/fonts/merriweather_700.ttf
        weight: 700
  - family: Montserrat
    fonts:
      - asset: assets/fonts/montserrat_300.ttf
        weight: 300
      - asset: assets/fonts/montserrat_400.ttf
        weight: 400
      - asset: assets/fonts/montserrat_500.ttf
        weight: 500
      - asset: assets/fonts/montserrat_600.ttf
        weight: 600
      - asset: assets/fonts/montserrat_700.ttf
        weight: 700
  - family: Nunito
    fonts:
      - asset: assets/fonts/nunito_300.ttf
        weight: 300
      - asset: assets/fonts/nunito_400.ttf
        weight: 400
      - asset: assets/fonts/nunito_500.ttf
        weight: 500
      - asset: assets/fonts/nunito_600.ttf
        weight: 600
      - asset: assets/fonts/nunito_700.ttf
        weight: 700
  - family: NunitoSans
    fonts:
      - asset: assets/fonts/nunito_sans_300.ttf
        weight: 300
      - asset: assets/fonts/nunito_sans_400.ttf
        weight: 400
      - asset: assets/fonts/nunito_sans_500.ttf
        weight: 500
      - asset: assets/fonts/nunito_sans_600.ttf
        weight: 600
      - asset: assets/fonts/nunito_sans_700.ttf
        weight: 700
  - family: OpenSans
    fonts:
      - asset: assets/fonts/open_sans_300.ttf
        weight: 300
      - asset: assets/fonts/open_sans_400.ttf
        weight: 400
      - asset: assets/fonts/open_sans_500.ttf
        weight: 500
      - asset: assets/fonts/open_sans_600.ttf
        weight: 600
      - asset: assets/fonts/open_sans_700.ttf
        weight: 700
  - family: Oswald
    fonts:
      - asset: assets/fonts/oswald_300.ttf
        weight: 300
      - asset: assets/fonts/oswald_400.ttf
        weight: 400
      - asset: assets/fonts/oswald_500.ttf
        weight: 500
      - asset: assets/fonts/oswald_600.ttf
        weight: 600
      - asset: assets/fonts/oswald_700.ttf
        weight: 700
  - family: PlayfairDisplay
    fonts:
      - asset: assets/fonts/playfair_display_400.ttf
        weight: 400
      - asset: assets/fonts/playfair_display_500.ttf
        weight: 500
      - asset: assets/fonts/playfair_display_600.ttf
        weight: 600
      - asset: assets/fonts/playfair_display_700.ttf
        weight: 700
  - family: Poppins
    fonts:
      - asset: assets/fonts/poppins_300.ttf
        weight: 300
      - asset: assets/fonts/poppins_400.ttf
        weight: 400
      - asset: assets/fonts/poppins_500.ttf
        weight: 500
      - asset: assets/fonts/poppins_600.ttf
        weight: 600
      - asset: assets/fonts/poppins_700.ttf
        weight: 700
  - family: PTSans
    fonts:
      - asset: assets/fonts/pt_sans_400.ttf
        weight: 400
      - asset: assets/fonts/pt_sans_700.ttf
        weight: 700
  - family: Raleway
    fonts:
      - asset: assets/fonts/raleway_300.ttf
        weight: 300
      - asset: assets/fonts/raleway_400.ttf
        weight: 400
      - asset: assets/fonts/raleway_500.ttf
        weight: 500
      - asset: assets/fonts/raleway_600.ttf
        weight: 600
      - asset: assets/fonts/raleway_700.ttf
        weight: 700
  - family: Roboto
    fonts:
      - asset: assets/fonts/roboto_300.ttf
        weight: 300
      - asset: assets/fonts/roboto_400.ttf
        weight: 400
      - asset: assets/fonts/roboto_500.ttf
        weight: 500
      - asset: assets/fonts/roboto_600.ttf
        weight: 600
      - asset: assets/fonts/roboto_700.ttf
        weight: 700
  - family: RobotoCondensed
    fonts:
      - asset: assets/fonts/roboto_condensed_300.ttf
        weight: 300
      - asset: assets/fonts/roboto_condensed_400.ttf
        weight: 400
      - asset: assets/fonts/roboto_condensed_500.ttf
        weight: 500
      - asset: assets/fonts/roboto_condensed_600.ttf
        weight: 600
      - asset: assets/fonts/roboto_condensed_700.ttf
        weight: 700
  - family: SourceSans3
    fonts:
      - asset: assets/fonts/source_sans_3_300.ttf
        weight: 300
      - asset: assets/fonts/source_sans_3_400.ttf
        weight: 400
      - asset: assets/fonts/source_sans_3_500.ttf
        weight: 500
      - asset: assets/fonts/source_sans_3_600.ttf
        weight: 600
      - asset: assets/fonts/source_sans_3_700.ttf
        weight: 700
  - family: Ubuntu
    fonts:
      - asset: assets/fonts/ubuntu_300.ttf
        weight: 300
      - asset: assets/fonts/ubuntu_400.ttf
        weight: 400
      - asset: assets/fonts/ubuntu_500.ttf
        weight: 500
      - asset: assets/fonts/ubuntu_700.ttf
        weight: 700
  - family: WorkSans
    fonts:
      - asset: assets/fonts/work_sans_300.ttf
        weight: 300
      - asset: assets/fonts/work_sans_400.ttf
        weight: 400
      - asset: assets/fonts/work_sans_500.ttf
        weight: 500
      - asset: assets/fonts/work_sans_600.ttf
        weight: 600
      - asset: assets/fonts/work_sans_700.ttf
        weight: 700